# Generated by Django 5.1.1 on 2024-10-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateField()),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat', to='surat.pengirim')),
            ],
        ),
    ]
