# Generated by Django 5.1.1 on 2024-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surat',
            new_name='Letter',
        ),
        migrations.RenameModel(
            old_name='Pengirim',
            new_name='Sender',
        ),
    ]
