# Generated by Django 5.1.1 on 2024-10-01 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0002_rename_surat_letter_rename_pengirim_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='tanggal',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
